### ISSUE TITLE
set correct output for default asound

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-livecd#11]
The following was reported by @hackrfbyt:
The first audio output way is HDMI.So sometimes vlc does not play audio.
we try like these:
aplay -l

```
/etc/asound.conf add :
defaults.ctl.card 1
defaults.pcm.card 1
defaults.timer.card 1

```
set the analog way for video players.

**Comment by ZeroChaos-** [comment]
we use gentoo livecd-tools which is supposed to handle such things.  I don't really want to change it
