### ISSUE TITLE
Unable to start X server when running live-cd on ryzen5 2400g with Vega 11 graphics card

### ISSUE THREAD

**Issue by ashishbishnoi** [pentoo/pentoo-livecd#13]

**Comment by blshkv** [comment]
Please post a log file. Also, do let us know if you have a solution

**Comment by ashishbishnoi** [comment]
Solved it. It works fine in uefi mode.

**Comment by blshkv** [comment]
I don't see how it could be uefi related but ok. Glad you managed to solve it ;-)
