### ISSUE TITLE
eix fails on LiveISO

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-livecd#14]
The ISO is missing /var/cache/eix and eix-update fails.

Here's the folder after "emerge -1 eix":

pentoo@pentoo ~ $ ls -alh /var/cache/eix
total 0
drwxr-xr-x 2 portage portage  60 May 11 08:58 .
drwxr-xr-x 1 root    root    100 May 11 08:58 ..
-rw-r--r-- 1 root    root      0 Mar  1 07:14 .keep_app-portage_eix-0

Here's the 'bug'-log:

pentoo@pentoo ~ $ sudo eix-update 
...
Writing database file /var/cache/eix/portage.eix...
**cannot open database file /var/cache/eix/portage.eix for writing (mode = 'wb')**

pentoo@pentoo ~ $ sudo emerge -1 eix
...
pentoo@pentoo ~ $ sudo eix-update 
Reading Portage settings...
...
Writing database file /var/cache/eix/portage.eix...
Database contains 20054 packages in 167 categories

**Comment by Wuodan** [comment]
Bug still exists in pentoo-amd64-hardened-2018.0_RC7.1.iso

**Comment by ZeroChaos-** [comment]
Per Filesystem Hierarchy Standard:
```
/var/cache : Application cache data. Such data are locally generated as a result of time-consuming I/O or calculation. The application must be able to regenerate or restore the data. The cached files can be deleted without loss of data.
```

if eix is too dumb to recreate what it needs in there, then the bug is in eix.  Please open a bug for them.  That said, I've updated fsscript to not wipe out /var/cache/eix

**Comment by blshkv** [comment]
Last time I checked, the problem was with the permission.
Please make sure that it belongs to ```portage``` (it was "root" if I'm not wrong).

**Comment by blshkv** [comment]
Taking of which, can you also generate its data using ```eix-update``` and distribute it together with ISO?
eix is a really useful tool, it is much faster to look for tools using it.

**Comment by ZeroChaos-** [comment]
I actually do eix-update it's just that I was wiping it's cache.  this should be fine baring any permission problems.

I need to know exactly what folder to chown to who.

**Comment by ZeroChaos-** [comment]
for example, /var/cache/edb is root.portage, do we really want portage.portage for eix?  that seems dangerous

**Comment by blshkv** [comment]
Any permission which allows to update it

**Comment by ZeroChaos-** [comment]
for now I'm doing root.portage, you can open a bug if that's not good enough
