### ISSUE TITLE
cpu default governor: ondemand

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-livecd#15]
the currect governor is set to ```performance```:
https://github.com/pentoo/pentoo-livecd/blob/master/livecd/amd64/kernel/config-4.16.11#L832

This is not good for a battery so we had to create a script at acpid:
https://github.com/pentoo/pentoo-overlay/blob/master/sys-power/acpid/files/acpid-pentoo-1.0.6-default.sh

The script adjusts cpu governor based on battery stage, etc. However, the same results can be archived by simply using ```CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND=y``` or conservative governors. ```Conservative``` just a bit slower to react, so ```ONDEMAND``` is the recommened default governor.

Please change it and remove acpid.

**Comment by ZeroChaos-** [comment]
wow, there is some terrible code right there.  well, you are half right.  it's set to conservative when it's on battery power, which is cripplingly slow.  it should be performance on ac and ondemand on battery, fixing now.

**Comment by blshkv** [comment]
wow, ondemand governor is no longer available if you use the latest ```intel_pstate``` driver (on intel?), see:

https://unix.stackexchange.com/questions/153693/cant-use-userspace-cpufreq-governor-and-set-cpu-frequency

That would require some research, but that new change (https://github.com/pentoo/pentoo-overlay/commit/3fecc357637422582053ee12e95a69f53fa05263#diff-e86de50bf30aa69f169e67cd0be515f7R44) might not work

**Comment by ZeroChaos-** [comment]
Yeah, Intel pstates should remain in performance which is fine.

**Comment by ZeroChaos-** [comment]
the more recent intel chips (say the last 5-6 years) save more battery in performance than ondemand because they are able to complete their work faster and then shut down cores.  I research battery stuff heavily, you didn't even know ondemand had been removed :-P

**Comment by blshkv** [comment]
true that, however not everybody have intel chips.

**Comment by ZeroChaos-** [comment]
AMD also has power saving features like intel for when cpu is not used.  They just didn't write their own cpu governor.  it's fine

**Comment by blshkv** [comment]
ok, an another point which need to be addressed:
AC - performance
batter - powersave.

I think it is not correct for the battery stage right now.

**Comment by ZeroChaos-** [comment]
powersave is a hard set of the lowest possible cpufreq, so no, we don't be setting that.

**Comment by blshkv** [comment]
this is not true, powersave is much more complex with intel_pstate. I was using it all the way after I migrated to the latest kernel without even noticing any slowness.
