### ISSUE TITLE
chromium on livecd built without KERNEL="linux"

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-livecd#16]
Right after installing from LiveCD, world-update wants to rebuild www-client/chromium with exactly the same version. The only difference is that the available version has KERNEL="linux" set and the installed does not.
I only report this because a chromium installation takes forever and maybe this can be avoided easily.

> $ eix www-client/chromium
> [I] www-client/chromium
>      Available versions:  67.0.3396.87^d ~68.0.3440.17^d ~68.0.3440.25^d [M]~69.0.3452.0^d [M]~69.0.3464.0^d {component-build cups custom-cflags gnome-keyring +hangouts jumbo-build kerberos neon pic +proprietary-codecs pulseaudio selinux +suid +system-ffmpeg +system-icu +system-libvpx +tcmalloc widevine **KERNEL="linux"** L10N="+am +ar +bg +bn +ca +cs +da +de +el +en-GB +es +es-419 +et +fa +fi +fil +fr +gu +he +hi +hr +hu +id +it +ja +kn +ko +lt +lv +ml +mr +ms +nb +nl +pl +pt-BR +pt-PT +ro +ru +sk +sl +sr +sv +sw +ta +te +th +tr +uk +vi +zh-CN +zh-TW"}
>      Installed versions:  67.0.3396.87^d(10:51:48 PM 06/18/2018)(cups hangouts pic proprietary-codecs pulseaudio suid -component-build -custom-cflags -gnome-keyring -jumbo-build -kerberos -neon -selinux -system-ffmpeg -system-icu -system-libvpx -tcmalloc -widevine L10N="am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk vi zh-CN zh-TW")

> $ emerge --deep --update --newuse world -vta
> [ebuild   R    ]   www-client/chromium-67.0.3396.87::gentoo  USE="cups hangouts (pic) proprietary-codecs pulseaudio suid -component-build -custom-cflags -gnome-keyring -jumbo-build -kerberos (-neon) (-selinux) (-system-ffmpeg) (-system-icu) (-system-libvpx) (-tcmalloc) -widevine" KERNEL="(**linux**%*)" L10N="am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk vi zh-CN zh-TW" 577,629 KiB

**Comment by ZeroChaos-** [comment]
gentoo changing eclasses and requiring a rebuild of 100 package is *annoying* but not everything which is annoying is a bug.
