### ISSUE TITLE
remove big stuff from non-full

### ISSUE THREAD

**Issue by ZeroChaos-** [pentoo/pentoo-livecd#18]
here are the biggest packages we install, see about removing what we can from non-full iso

180M icedtea-3.8.0.tbz2
575M rust-1.25.0.tbz2
129M android-sdk-update-manager-23-r1.tbz2
140M mesa-17.3.9.tbz2
316M gcc-7.3.0-r3.tbz2  -- we really can't remove gcc
132M linux-firmware-20180717-r1.tbz2  -- we could strip a bunch of things out of linux-firmware most likely
143M db-5.3.28-r2.tbz2
119M chromium-68.0.3440.75.tbz2

**Comment by blshkv** [comment]
you can remove chrome/chromium from non-ful. Firefox is a more practical browser for a pentester. it is less strict and we provide hacking plugins for FF mostly

**Comment by ZeroChaos-** [comment]
Chromium has a 60% market share, it is the browser people want.

Firefox on the other hand, seems to runtime require rust, which makes me
really want to kill it.

**Comment by blshkv** [comment]
you should disable debugging instead

 * Packages now in '/usr/portage/packages':
 * media-libs/mesa-17.3.9: 13.3M

**Comment by ZeroChaos-** [comment]
the livecd already doesn't include debugging data.  the packages do, so
those sizes are a bit inaccurate.

I really don't want to remove debugging data from the packages as it's the
only way we can actually troubleshoot something.  that said, I've never
used it, and I suspect most people wouldn't even know how, so maybe drop
-ggdb from the build use flags?

**Comment by blshkv** [comment]
Yeap, you compile binaries for developers but shared with uses in production eventually. That's was one of the reason why I never used default profile and avoid binaries as much as possible

**Comment by ZeroChaos-** [comment]
Ever other distro on the planet compiles this way, the difference is the
package managers for other distros split debug files into their own
packages. Gentoo lacks the support :-(

**Comment by Wuodan** [comment]
Please put vim back on the ISO.
Right now there's only nano.

**Comment by blshkv** [comment]
Ca you use vi instead?

**Comment by ZeroChaos-** [comment]
this is mostly all well and done now
