### ISSUE TITLE
disable opencl by default

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-livecd#21]
the end users are having a problem with this flag later, see:
https://github.com/pentoo/pentoo-overlay/issues/319

This flag is enabled in livecd:
https://github.com/pentoo/pentoo-livecd/blob/master/livecd/specs/fsscripts/fsscript-livecd-stage2.sh#L144
https://github.com/pentoo/pentoo-livecd/blob/master/livecd/specs/fsscripts/fsscript-livecd-stage2.sh#L149

But it is masked for mesa:
https://github.com/pentoo/pentoo-overlay/blob/master/profiles/pentoo/base/package.use.mask#L11

These, users face this unclear abovementioned error

**Comment by blshkv** [comment]
... and we need "pentoo-cracking +opencl" in the same time. So it sounds like we do want the global opencl USE flag.

**Comment by ZeroChaos-** [comment]
opencl needs to be enabled by default for the livecd or compatible users won't have the support.

unfortunately, gentoo basically only supports opencl for nvidia users, and not intel or amd users.  Someone needs to fix that, it's non-trivial.  until then, nothing sane can be done.

The closest thing to sane which can be done quickly is to have livecd remove opencl at boot if compatible hardware isn't found.
