### ISSUE TITLE
arm64 Kernel config 

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-livecd#22]
[ https://github.com/necrose99/arm64-portage/tree/master/kernels ]

[linux-4.16.11-pentoo.config.zip](https://github.com/pentoo/pentoo-livecd/files/2329670/linux-4.16.11-pentoo.config.zip)

most devices set to baked in .. fail safe to boot most... 
@ home most user will be rpi3 or b+'s or  rock64 
however most servers are set to bakedin also..   Y and not M 
With Better Testing , can likely relax some to M. 
most U-BOOT's now can do EFI firmware for grub , just getting grub to setup uboot on devices for 
/boot/efi (other fat32 files here)  /boot / /var/fake-swap1  , etc... 
so having to bake all to a kernel-efi bin may not be required.  hopefully not.. 

sys-kernel/linux-pentoo (amd64/x86)   or sys-kernel/linux-pentoo-arm   sys-kernel/linux-pentoo-arm64 
point being I have Gentoo/Pentoo kernel/s in dev/vdb volume on scaleway but pretty much backed with mkstage4 ...  however not packaged.. a basic get the box up bin kernel
point being is I could pull kernel to HW for testing out of chroot,,  and not very emerge linux-pentoo-bin.tgz  wala kernel ...  after pulling from dev-chroot to package host... for others.. 

eventually aim to have FS image of base line pentoo...  soonish..  for a few IOT class devices. 

sabayon dose thiers with eclasses.. sys-kernel/linux-sabayon ...  however use config from git etc.. 

https://gpo.zugaina.org/sys-kernel/intel-kernel-bin64  gentoo bin kernel 
 

anyhow arm7hf /arm64 Pentoo-experimental  & **pentoo mirroring** on my to do list...  of VPS to'dos...

**Comment by ZeroChaos-** [comment]
please don't open issues for this kind of thing.  Also, I'm not hosting binary kernels in a format that gentoo doesn't support.
