### ISSUE TITLE
Persistence usb

### ISSUE THREAD

**Issue by blackdon2019** [pentoo/pentoo-livecd#26]
Hello, I follow how the Pentoo site says to use changes = / dev / sdXY and it doesn't work, when I upgrade Pentoo it says it doesn't have enough space on the flash drive ... can anyone help me

**Comment by blshkv** [comment]
Cam we ban him? This is annoying

**Comment by ZeroChaos-** [comment]
be my guest, I only know how to block him

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/490
