### ISSUE TITLE
Pentoo usb error

### ISSUE THREAD

**Issue by GhostBlackd** [pentoo/pentoo-livecd#29]
When I try to persist usb it does not work, I follow the steps of the official site and even then when I boot the system, I type changes = / dev / sdXY changing for the value corresponding to my usb and yet when doing: emerge --sync or any other command to upgrade or install something I get an error, which does not have enough space on the device even though I still have a partition with more than 4gb free

**Comment by blshkv** [comment]
this user with useless reports is back (https://github.com/pentoo/pentoo-livecd/issues/26)

@GhostBlackd see how to report it properly:
https://github.com/pentoo/pentoo-livecd/issues/30
