### ISSUE TITLE
After boot menu, black big box ... stuck

### ISSUE THREAD

**Issue by fe77** [pentoo/pentoo-livecd#31]
Hi,
I installed a pentoo image on an usb stick, and just after the boot menu (whatever option I take) I get this black box, and it is stuck.
I checked with another stick with a kali linux, this black box appears, but disappears afte 3 seconds… then the Kali appears (GUI).
Could you help me to fix this behavior with pentoo ?
Thanks.

**Comment by blshkv** [comment]
please provide more details using the following https://wiki.gentoo.org/wiki/Bugzilla/Bug_report_guide

**Comment by ZeroChaos-** [comment]
there were some problems relating to this on amd systems which should be resolved in newer isos
