### ISSUE TITLE
NetworkManager: Not authorized to control networking.

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-livecd#32]
**NetworkManager fails when clicking on wlan connection.**

**Steps:**

1. Boot ISO from USB
2. after login: sudo /etc/init.d/NetworkManager start
3. startx
4. Click on NetworkManager icon on top-right
5. Select a WI-FI Network
6. NetworkManager fails

**Screenshot:**
![NetworkManager_NotAuthorizedToControlNetworking](https://user-images.githubusercontent.com/1812358/74290778-30770a00-4d33-11ea-8670-c88c686111a2.png)

**Log snippet** from /var/log/everything/current:
`[NetworkManager] <info>  [1581456841.7210] audit: op="connection-add-activate" pid=9750 uid=1000 result="fail" reason="Not authorized to control networking."`

**Affected ISO:**
/isos/daily-autobuilds/Pentoo_Full_amd64_hardened/pentoo-full-amd64-hardened-2020.0_r1_p20200123.iso
The previous ...p20200209.iso does not show the problem

**Possible solution:**
From [https://wiki.gentoo.org/wiki/NetworkManager#Fixing_nm-applet_insufficient_privileges](url):
Create the following file:
/etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules
...

If you add the file, pls chown it to polkit like the other file in that folder:
> $ sudo ls -alh /etc/polkit-1/rules.d/
-rw-r--r-- 1 polkitd root  321 Nov 12 10:21 50-default.rules
-rw-r--r-- 1 polkitd root  179 Feb 11 23:41 50-org.freedesktop.NetworkManager.rules

**emerge --info:**
[emerge--info.txt](https://github.com/pentoo/pentoo-livecd/files/4189208/emerge--info.txt)

**Comment by ZeroChaos-** [comment]
unable to replicate on new isos, seems like a momentary glitch somehow.
