### ISSUE TITLE
RelEng :: unified build system

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-livecd#33]
RelEng :: unified build system fully compliant with gentoo plus web interface. 

   Please provide clear description how the process take place and how to prepare build system. What kind of custom modification are in use comparing with plain gentoo releng.

**Comment by ZeroChaos-** [comment]
I've had to fork catalyst and quit the gentoo releng team after ten years due to new leadership's "most fast and break things" policy of breaking the ability to build working releases
