### ISSUE TITLE
grub: error file /grub/locale/C.gmo not found

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-livecd#36]
This text pops up really quick just before the colorful grub display is shown.
![grub_locale_C_not_found](https://user-images.githubusercontent.com/1812358/83451922-09665480-a458-11ea-89d1-1f154e6b66f3.jpg)

It happens after installing Pentoo with the installer, but I think it also happens on the live USB-stick.
Don't have time to check live usb-stick right now, so I just park this by reporting it here.

**Comment by Wuodan** [comment]
Does not happen on the LiveUSB, closing and moving to https://github.com/pentoo/pentoo-overlay/issues/645

**Comment by blshkv** [comment]
it might be pentoo-installer then? Not pentoo-overlay for sure
