### ISSUE TITLE
Permission issue on /var/cache/distfiles => can't emerge live packages

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-livecd#37]
On the iso pentoo-full-amd64-hardened-2020.0_p20200527.iso, `/var/cache/distfiles` is owned by root:root instead of root:portage and group-permissions are r-x not rwx.
Thus I can't emerge live packages which use git, because portage cannot create `/var/cache/distfiles/git3-src`.

**Error documentation:**
`mkdir: cannot create directory ‘/var/cache/distfiles/git3-src’: Permission denied`

output of `ls -alh /var/cache` on the ISO:
`drwxr-xr-x 1 root root      3 May 17 07:23 distfiles`

output of `ls -alh /var/cache` after installation to hd:
`drwxrwxr-x  3 root portage  32K Jun  6 08:37 distfiles`

**Steps to fix:**
`sudo chown root:portage /var/cache/distfiles`
`sudo chmod g+w /var/cache/distfiles`

**other error output:**
`* ERROR: pentoo/pentoo-installer-99999999::pentoo failed (unpack phase):` 
` *   Unable to create /var/cache/distfiles/git3-src` 
` * ` 
` * Call stack:` 
` *     ebuild.sh, line  125:  Called src_unpack` 
` *   environment, line 1090:  Called git-r3_src_unpack` 
` *   environment, line 1027:  Called git-r3_src_fetch` 
` *   environment, line 1021:  Called git-r3_fetch` 
` *   environment, line  789:  Called _git-r3_set_gitdir 'https://github.com/pentoo/pentoo-installer.git'` 
` *   environment, line  434:  Called die` 
` * The specific snippet of code:` 
` *           mkdir -p "${EGIT3_STORE_DIR}" ) || die "Unable to create ${EGIT3_STORE_DIR}";`

**Comment by ZeroChaos-** [comment]
I feel like I've fixed this 1000 times, and in fact I have:
https://github.com/pentoo/pentoo-livecd/blob/master/livecd/specs/make_modules.sh#L73
https://github.com/pentoo/pentoo-livecd/blob/master/livecd/specs/fsscripts/fsscript-livecd-stage2.sh#L124

None of that seems to matter though, something isn't working right and I have no idea what.  It's correct in the tmpdir for the modules for sure though, so make_modules.sh pretty much has to be correct....

**Comment by ZeroChaos-** [comment]
The modules file is confirmed correct, /mnt/livecd is wrong but that's the lower branch so that shouldn't matter?  I don't know what's going on here, I added one more chown to see if it helps, just for fun.

**Comment by ZeroChaos-** [comment]
I fixed this by dropping a file in /etc/local.d that fixes the permissions on boot.  I have no idea how or why this is messed up, but it's sure to be fixed now (tested and functional)
