### ISSUE TITLE
Pentoo Full iso are asking for username and password

### ISSUE THREAD

**Issue by insanitus** [pentoo/pentoo-livecd#40]
Hi !

  I just download the _live cd_ [1] and when i run the live iso, this just _ask for username and password_
and I can't log in.

 ( I try with some default ones, but I don't have success )

Thanks in advance.

 [1]pentoo-full-hardened-2020.0_p20200825

**Comment by ZeroChaos-** [comment]
Apologies for that know bug in the last few days isos.  You can switch to vt1 to set your password, or just download a new iso as the bug is fixed now.
