### ISSUE TITLE
NetworkManager and XFCE windows manager don't respond via terminal

### ISSUE THREAD

**Issue by insanitus** [pentoo/pentoo-livecd#41]
Hi !

 When I try to use these commands at the begging of the boot

  _$ /etc/init.d/NetworkManager start
  $ startx_ 

 The system not respond.

Also i see some message like;

mistake in
  /usr/sbin/livecd-setpass line 23
  /usr/sbin/livecd-setpass line 30
  /usr/sbin/livecd-setpass line 36,39,40,45,50

 
The iso version I download is _pentoo-full-hardened-2020.0_p20200827.iso_ 

 Thanks in advance for the time you take to read and solve this issue, have a nice day (n__n)

**Comment by ZeroChaos-** [comment]
unable to replicate, no errors provided, nothing to do here.
