### ISSUE TITLE
Unable to start the windows manager

### ISSUE THREAD

**Issue by insanitus** [pentoo/pentoo-livecd#42]
Hi!

XFCE windows manager not work

Steps:

    1. Download the full-hardened iso from https://www.pentoo.ch/isos/daily-autobuilds/
    2. Boot ISO from livecd
  
![Pentoo-test_1](https://user-images.githubusercontent.com/22409665/91651682-40f89300-ea7f-11ea-8451-3a4154ce2e17.png)

 ``` 3.Try to start the windows manager```

![Pentoo-test_2](https://user-images.githubusercontent.com/22409665/91651675-2c1bff80-ea7f-11ea-8bbd-a8a39df79dbb.png)

Thanks in advance for the time you take to read and solve this issue, have a nice day (n__n)

**Comment by ZeroChaos-** [comment]
Which iso is this? Did you boot with verify?

**Comment by insanitus** [comment]
Hi @ZeroChaos- 

**Which iso is this?**
```pentoo-full-hardened-2020.0_p20200827.iso```

 **Did you boot with verify?**
```No```






 I appreciated the time you take to fix this issue, have a nice day.

**Comment by ZeroChaos-** [comment]
Boot with verify, it will tell you your iso is corrupt.  Unable to replicate here.  You can check the checksums of the iso to make sure your download was okay and try remaking your USB stick.
