### ISSUE TITLE
installation on virtualbox fails

### ISSUE THREAD

**Issue by hyOzd** [pentoo/pentoo-livecd#44]
I'm trying to install pentoo on a virtualbox using daily live image pentoo-full-amd64-hardened-2020.0_p20201213. I get this error at the file copying step:

```
Failed to rsync
'/mnt/gentoo/root/'. See the log output for more information.
```

This happens at the almost at the beginning of the process right after 'uncompress' is completed.

I think this is the relevant section from the install log:
```
+ rsync -av --progress --exclude=/root/.bashrc '/root/*' /mnt/gentoo/root/
++ dialog --backtitle 'Pentoo Installation' --aspect 15 --gauge 'Syncing /root ...' 0 0
+ _ANSWER=
+ _DIALOGRETURN=0
+ '[' -n '' ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 255 ']'
+ '[' 0 -ne 0 ']'
+ echo -n ''
+ return 0
+ _RET_SUB=23
+ '[' 23 -ne 0 ']'
+ show_dialog --msgbox 'Failed to rsync '\''/mnt/gentoo/root/'\''. See the log output for more information' 0 0
+ _ARGUMENTS=()
```

This is the full content of the callback log:

```
        sending incremental file list
        rsync: [sender] link_stat "/root/*" failed: No such file or directory (2)
         
        sent 19 bytes  received 12 bytes  62.00 bytes/sec
        total size is 0  speedup is 0.00
        rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]
```

Link to full install log: https://pastebin.pl/view/e808abbe

I couldn't find any other log that seem relevant, please let me know if there is more information that i should provide.

**Comment by ZeroChaos-** [comment]
Thanks for the bug report.  This has already been fixed in the latest pentoo-installer but new isos have not been generated due to other build failures.  Please "emerge --sync && emerge -1 pentoo-installer" until a new iso comes out.

**Comment by hyOzd** [comment]
@ZeroChaos- Thanks for the workaround!
