### ISSUE TITLE
Pyrit tool can't be installed and profile is deprecated

### ISSUE THREAD

**Issue by insanitus** [pentoo/pentoo-livecd#45]
Hi !

 When I try to install the pyrit tool 

 ```sudo emerge -1 net-wireless/pyrit-0.5.0_p20180801::pentoo```

I get this error:

!!! Error fetching binhost package info from 'https:// pentoo.emjay-embedded.co.uk/Packages/amd64-hardened'
!!! <urlopen error [Errno -3] Temporary failure in name resolution>

!!! Error fetching binhost package info from 'https:// ftp.acc.umu.se/mirror/pentoo.ch/Packages/amd64-hardened'
!!! <urlopen error [Errno -3] Temporary failure in name resolution>

!!! Error fetching binhost package info from 'https:// pentoo.osuosl.org/Packages/amd64-hardened'
!!! <urlopen error [Errno -3] Temporary failure in name resolution>

**!!! Your current profile is deprecated and not supported anymore.
!!! Use eselect profile to update your profile.
!!! Please upgrade to the following profile if possible:

        default/linux/amd64/17.1/hardened**

To upgrade do the following steps:

The amd64 17.1 profiles switch to a more standard 'no SYMLINK_LIB' 
multilib layout, and require an explicit migration.
The migration is performed using the app-portage/unsymlink-lib tool.
The following steps can be used to upgrade your system:

1. Sync and upgrade your system to the newest package versions
   to reduce the risk of issues.

2. Install the tool:
      emerge -1v app-portage/unsymlink-lib

3. Run 'unsymlink-lib --analyze' and check the output for obvious
   mistakes.  If you need to perform any changes to the system, remember
   to run 'unsymlink-lib --analyze' again afterwards.

[past this point do not call emerge or modify /usr manually]

4. This is a very good time to make a backup.

5. Run 'unsymlink-lib --migrate'.  You can add '--pretend' first to see
   what is going to happen.

6. Reboot your system.  Check if important programs work.
   In particular, verify that e.g. 'emerge --info' works (but do not
   install anything).  If you hit any serious problems, you can use
   'unsymlink-lib --rollback' to revert the changes and return to
   step 3.

7. Run 'unsymlink-lib --finish'.  You can add '--pretend' first to see
   what is going to happen but note that you're going to see a very long
   list of files to remove.

8. Switch the profile, e.g.:
     eselect profile set default/linux/amd64/17.1/desktop

[at this point you can start using emerge again. emerge will then 
 not display this message anymore, but the remaining steps are still 
 required!]

9. Rebuild gcc:
       emerge -1v sys-devel/gcc:9.3.0
      [ repeat for other slots you will be using ]

10. If you are using a multilib profile, rebuild all 32-bit packages.
    This can be done using:
       emerge -1v --deep /lib32 /usr/lib32 /usr/lib/llvm/*/lib32

11. Once the last 32-bit package is rebuilt, your package manager
    should remove the orphaned /lib32 and /usr/lib32 symlinks.  If that
    does not happen, remove them manually:
       rm /lib32 /usr/lib32

For known issues, please see bug #506276 [1].  If you have any problems
with the new profiles or the migration procedure, please report a bug
and make it block the tracker.

[1] https:// bugs.gentoo.org/506276

**!!! 'net-wireless/pyrit-0.5.0_p20180801::pentoo' is not a valid package atom.
!!! Please check ebuild(5) for full details.**

I take an eye in the pyrit repositry https://github.com/JPaulMora/Pyrit 
and I notice the tool is under python ver 2

"Pyrit is old, is outdated and it's still Python2 I am currently attempting to rewrite it from scratch, so thanks for all the stars but remember to keep an eye for Python3 version."

Cheking the python version in the system is the version 3

```Is any chance that pyrit would work in the system?```

Thanks in advance for the time you take to read and solve this issue, have a nice day (n__n)

```

**Comment by ZeroChaos-** [comment]
pyrit was removed from pentoo a few days ago, and the profile hasn't been deprecated for months.  please run pentoo-updater at least twice, hopefully it will get you up to date.

**Comment by insanitus** [comment]
Thanks @ZeroChaos-  for the details :+1:  :)

 Have a nice day
