### ISSUE TITLE
Please add thunderbolt support to you kernel

### ISSUE THREAD

**Issue by YongBinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [pentoo/pentoo-livecd#49]
https://wiki.gentoo.org/wiki/USB/Guide#USB_Type-C_and_Thunderbolt

The thunderbolt module provides more protection than xhci_pci when dealing with a new version usb-c port.

Would be good if you publish the configuration you used to compile your kernel.

**Comment by ZeroChaos-** [comment]
We do https://github.com/pentoo/pentoo-overlay/tree/master/sys-kernel/pentoo-sources/files

**Comment by YongBinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [comment]
Hi, thank you for providing the link to the files. I must have missed something when trying to use the driver.
I got following error when I was trying to install the module.

> $ sudo insmod thunderbolt
> insmod: ERROR: could not load module thunderbolt: No such file or directory

I am not familiar to linux kernel, is the kernel compile option related to the module? What should I do if I want the protection from the driver to fight against DMA attack?

**Comment by ZeroChaos-** [comment]
Everything thunderbolt related works correctly by default.  If you have questions about how please use google.
