### ISSUE TITLE
add NVIDIA-CUDA licence list

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-livecd#6]
subj. "emerge" flags a warning. It is installed by default but it is not in the list.

**Comment by ZeroChaos-** [comment]
that's right, I didn't want to add the license to ACCEPT_LICENSE for all users, but I don't think anything legal prevents me from doing so.  Shall I just add it to the profile?  Or better to add it to the livecd make.conf?

**Comment by blshkv** [comment]
I was looking around for options and found chromium page:
https://www.chromium.org/chromium-os/licensing/building-a-distro
```Default Accepted Licenses
* -@EULA
```

sadly, it doesn't include nvidia. So please add the keyword to livecd only since you decided to ship drivers preinstalled anyway. Users would still need to accept it if they need it.

**Comment by ZeroChaos-** [comment]
Actually, you can clearly see that the drivers are NOT shipped on the livecd at all:
https://github.com/pentoo/pentoo-livecd/blob/master/livecd/specs/fsscripts/fsscript-livecd-stage2.sh#L419
https://github.com/pentoo/pentoo-livecd/blob/master/livecd/specs/livecd-stage2-common.spec#L90

In fact, I went through great pains to autodetect the correct drivers and build them at boot time:
https://github.com/pentoo/pentoo-overlay/blob/master/pentoo/pentoo-livecd/files/binary-driver-handler.initd-2014.3-r10

Reading the cuda license it's not clear if what we are doing is prohibited, the license text is pretty unclear when I read it.  I can accept the license on the livecd for now and determine how to handle this going forward.
