### ISSUE TITLE
Windows 10 vbox pentoo ISO's hang at Grub. (2015's)

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-livecd#9]
VirtualBox Graphical User Interface
Version 5.1.18 r114002 (Qt5.6.2)
pentoo-amd64-hardened-2015.0_RC5.iso  , hardened x86 , any of those do hang. 

pentoo-amd64-default-2017.0_RC5.2_pre20170329.iso going to try one of the newer beta's.
anyhow I'm going to clean install my Sabayon init is broken-ish  from pentoo overlay.. 
and windows in short order ,  was getting squashes for Docker |  pentoo-amd64-default-2017.0_RC5.2.tar.xz  add dropbox and push to quay.io and or hub.docker.com a snap of the installs four building.  can try stuff in docker without much issues.   and drop the tarballs in the packages folder and if something breaks not kill your pentoo /Gentoo/Sabayon install.  also if i can use raw Sqashfiles , it might go really well.  save the conversion , and also could script thier packing on build server.

**Comment by blshkv** [comment]
Please explain how can we help in 2 worlds or make a pull request. I'm unable to understand what this issue is about.

**Comment by necrose99** [comment]
**virtualbox , pentoo hangs at boot.  pentoo-amd64-default-2017.0_RC5.2 now also..** 

was just trying to dump the sqashfiles out to usb as targz or xz ,  however 2015 or likewise 2017 iso's hang on 
GRUB and die @ boot   
updated windows 10 virtualbox last night ...   and tried to fire up Pentoo in a box NO GO...  
(so much for converting to docker to do test builds of pentoo bins for sab or etc install) 

{my Linux install is init is kinda borked , **_and was being lazy_** , going to be a bit to fix it) 

**GRUB** is all you see and it hangs for some time , no pentoo splash or etc.  
Pentoo ISO has booted in virtualbox on windows almost always.  even checked for iso sigs , and good. 
however its newer VBOX versions. 

Sabayon Linux 16.11 iso boots as dose the daily.

**Comment by blshkv** [comment]
I think the latest beta is broken and does not boot at all

**Comment by ostree** [comment]
Hi, there is a problem over the boot but I can boot from the latest live CD
- just type 'exit' when console shows up right after the init process. This
way you should complete the boot process and progress and complete an
installation, regards

**Comment by blshkv** [comment]
It would be good to provide some information:

This bug is too old and a new iso has been released. It were a lot of changes and this bug is likely fixed.

I have hit an another problem (SMP message) recently, see the following
https://forums.virtualbox.org/viewtopic.php?f=6&t=84158

The provided workaround solved it too.
